name: ssh command
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}

      - name: Deploy & run Cypress on staging
        run: |
          ssh ${{ steps.ssh.outputs.SERVER }} <<'EOF'
          set -euo pipefail

          # 1) デプロイ
          bash /app/ryuta_takaki/deploy.sh ryuta_takaki

          # 2) ホームディレクトリ下の ci ディレクトリへ
          cd /ci
          EOF
